name: Debug action
description: Action to debug stuff

inputs:
  plugin-slug:
    description: The WordPress plugin slug
    type: string
    required: true
  version-count:
    description: The number of released versions to return
    type: number
    default: '3'

runs:
  using: "composite"
  steps:
    - name: Debug details
      id: debug-details
      shell: bash
      run: |
        echo "plugin-slug: ${{ inputs.plugin-slug }}"
        echo "version-count: ${{ inputs.version-count }}"
        which curl