services:
   wordpress:
     volumes:
       - /Users/rado/Projects/woocommerce/plugins/woocommerce:/var/www/html/wp-content/plugins/woocommerce
       - /Users/rado/Projects/product-feed:/var/www/html/wp-content/plugins/open-ai-feed
     #build:
      # args:
         # - XDEBUG_REMOTE_PORT=9001 # IDE/Editor's listener port
                           