services:
  wordpress:
    build: ./docker/wordpress_xdebug
    image: wordpress-xdebug
    container_name: woocommerce_stripe_wordpress
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - "8072:80"
    env_file:
      - default.env
    volumes:
      - ./docker/wordpress:/var/www/html/
      - ./docker/logs/apache2/:/var/log/apache2
      - ./docker/logs/php/:/var/log/php
      - .:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe
      - ./tests/phpunit:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe/tests/phpunit
      - docker_directory:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe/docker
      - node_modules:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe/node_modules
      - phpstan_stubs:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe/phpstan-stubs
      - release_directory:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe/release
      - ./docker/dev-php.ini:/usr/local/etc/php/conf.d/dev-php.ini
      - ./docker/override-php-error-logging.ini:/usr/local/etc/php/conf.d/override-php-error-logging.ini
      - ./docker/bin:/var/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    container_name: woocommerce_stripe_mysql
    image: mariadb:latest
    ports:
      - "5668:3306"
    env_file:
      - default.env
    volumes:
      - ./docker/data:/var/lib/mysql
  phpMyAdmin:
    container_name: woocommerce_stripe_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8073:80"
    env_file:
      - default.env
# Set up volumes to prevent files from the host machine being exposed to the container and possible external access.
volumes:
   docker_directory:
   node_modules:
   phpstan_stubs:
   release_directory:

