name: Add changelog entry to a file

inputs:
  CHANGELOG_ENTRY:
    description: 'The changelog entry to add to the file'
    default: ''
  FILENAME:
    description: 'The file to add the changelog entry to'
    default: './changelog.txt'

description: 'Add a changelog entry to a file'
runs:
  using: composite
  steps:
    - name: 'Add changelog entry to a file'
      id: add_changelog_entry
      uses: actions/github-script@v6
      with:
        script: |
          const path = require('path');
          const scriptPath = path.join(__dirname, 'add-changelog.js');
          require(scriptPath);
