name: Add changelog entry to a file

inputs:
  CHANGELOG_ENTRY:
    description: 'The changelog entry to add to the file'
    default: ''
  FILENAME:
    description: 'The file to add the changelog entry to'
    default: './changelog.txt'

description: 'Add a changelog entry to a file'
runs:
  using: composite
  steps:
    - name: 'Add changelog entry to a file'
      id: add_changelog_entry
      uses: actions/github-script@v6
      with:
        run: |
          const fs = require( 'node:fs' );
          
          const token = 'xxxx-xx-xx =';
          const filename = ${{ inputs.FILENAME }};
          
          const changelog = fs.readFileSync( filename, 'utf-8' );
          const changelog_parts = changelog.split( token );
          
          changelog_parts[1] = '\n' + ${{ inputs.CHANGELOG_ENTRY }} + changelog_parts[1];
          
          const updatedChangelog = changelog_parts.join( token );
          
          fs.writeFile( filename, updatedChangelog, err => {
            if ( err ) {
              console.error( 'Unable to update changelog entries in ' + ${{ inputs.FILENAME }} );
            }
          } )
          