#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED="\033[1;31m"
NO_COLOR="\033[0m"

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(trunk|develop|release/*)"

# Only show warning for 'develop', 'trunk' and 'release/...' branches.
if ! [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
	exit 0
fi

# Ask for confirmation, anything other than 'y' or 'Y' is considered as a NO.
echo "\nYou're about to push to ${RED}${BRANCH}${NO_COLOR} 😱, is that what you intended? [y|n] \c"
read -n 1 -r < /dev/tty
echo "\n"
if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
	exit 0
fi

exit 1
