name: PHP tests

on:
  pull_request

jobs:
  beta-compatibility:
    strategy:
      fail-fast: false
      matrix:
        woocommerce: [ 'beta' ]
        wordpress:   [ 'latest' ]
        php:         [ '7.4', '8.0', '8.1' ]

    name: Beta (PHP=${{ matrix.php }}, WP=${{ matrix.wordpress }}, WC=${{ matrix.woocommerce }})
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      wp-version: ${{ matrix.wordpress }}
      wc-version: ${{ matrix.woocommerce }}
      php-version: ${{ matrix.php }}
