name: 'Generate changelog'

on:
  pull_request:
    types: [edited]
    branches:
      - trunk
      - develop

permissions: {}

jobs:
  generate_changelog:
    name: 'Generates a changelog entry'
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: 'Collect changelog data from PR description'
        run: |
          chmod +x .github/scripts/generate-changelog.sh
          .github/scripts/generate-changelog.sh -p "${{ github.event.pull_request.body }}" -o $GITHUB_OUTPUT
        id: collect_changelog_data
        
      - name: 'Add changelog entry to changelog.txt'
        uses: ./.github/actions/add-changelog-entry
        with:
          CHANGELOG_ENTRY: ${{ steps.collect_changelog_data.outputs.CHANGELOG_ENTRY }}
          FILENAME: './changelog.txt'
          
      - name: 'Add changelog entry to readme.txt'
        uses: ./.github/actions/add-changelog-entry
        with:
          CHANGELOG_ENTRY: ${{ steps.collect_changelog_data.outputs.CHANGELOG_ENTRY }}
          FILENAME: './readme.txt'
          
      - name: 'Commit changes'
        run: |
            git config user.name "bot-wc-stripe"
            git config user.email "bot-wc-stripe@users.noreply.github.com"
            git add changelog.txt
            git add readme.txt
            git commit -m "Add changelog entry for PR ${{ github.event.pull_request.number }}"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
        id: commit_changes
        