name: 'Issue Gardening'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  issue-gardening:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'woocommerce/woocommerce-gateway-stripe' }}
    strategy:
      matrix:
        include:

          - name: 'Issues that require more info'
            message: 'Help us move this issue forward. This issue is being marked stale since it has no activity after 15 days of requesting more information. Please add info requested so we can help move the issue forward.'
            days-before-stale: 15
            days-before-close: -1
            only-labels: 'status: needs more info'
            remove-stale-when-updated: true
            stale-issue-label: 'status: stale'

          - name: 'Issues without activity for 5 months'
            message: "Hi,\nThis issue has gone 150 days (5 months) without any activity. This means it is time for a check-in to make sure it is still relevant. If you are still experiencing this issue with the latest version, you can help the project by responding to confirm the problem and by providing any updated reproduction steps.\nThanks for helping out."
            days-before-stale: 150
            days-before-close: -1
            only-labels: ''
            remove-stale-when-updated: true
            stale-issue-label: 'status: needs confirmation'

          - name: 'Issues without activity for 6 months'
            message: 'This issue has gone 180 days (6 months) without any activity.'
            days-before-stale: 30
            days-before-close: -1
            only-labels: 'status: needs confirmation'
            remove-stale-when-updated: true
            stale-issue-label: 'status: stale'

    steps:
      - name: Update issues
        uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: ${{ matrix.message }}
          days-before-stale: ${{ matrix.days-before-stale }}
          days-before-close: ${{ matrix.days-before-close }}
          only-labels: ${{ matrix.only-labels }}
          remove-stale-when-updated: ${{ matrix.remove-stale-when-updated }}
          stale-issue-label: ${{ matrix.stale-issue-label }}
