name: JS tests

on:
  pull_request

jobs:
  test:
    name:    JS testing
    runs-on: ubuntu-latest
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      # install pnpm
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      # use the node version defined in nvmrc
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      # install dependencies and run tests
      - run: pnpm install --frozen-lockfile && pnpm run test:js
