name: Linting

on:
  pull_request

env:
  WP_VERSION: latest
  WC_VERSION: latest

jobs:
  changes:
    name: Check for code changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      code: ${{ steps.detect.outputs.code }}
    steps:
      - uses: actions/checkout@v6.0.3
      - id: detect
        uses: ./.github/actions/detect-code-changes

  php_lint:
    name:    PHP linting
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest
    steps:
      # clone the repository
      - uses: actions/checkout@v6.0.3
      # enable dependencies caching
      - uses: actions/cache@v5
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # setup PHP, but without debug extensions for reasonable performance
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: '7.4'
          tools:       composer
          coverage:    none
      # install dependencies and run linter
      - run: composer install --no-progress && ./vendor/bin/phpcs --standard=phpcs.xml.dist -n $(git ls-files | grep .php$)
  js_css_lint:
    name: JS & CSS linting
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-latest
    steps:
      # clone the repository
      - uses: actions/checkout@v6.0.3
      # use the node version defined in nvmrc
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      # enable dependencies caching
      - uses: actions/cache@v5
        with:
          path: ~/.cache/composer/
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      - uses: actions/cache@v5
        with:
          path: ~/.npm/
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      # install dependencies and run linter
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:css
