name: PHP code coverage

on:
  push:
    paths:
      - '**.php'

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    if: ${{ ! contains( github.event.head_commit.message, 'Merge branch' ) }}
    runs-on: ubuntu-22.04
    name: PHP=8.1, WP=6.7, WC=9.5.2
    env:
      PHP_VERSION: '8.1'
      WP_VERSION: '6.7'
      WC_VERSION: '9.5.2'
    steps:
      - name: Get Changed Files
        id: get-changed-files
        uses: hanseltimeindustries/get-changed-files@v1.1.2
        with:
          format: 'space-delimited'
          filter: '**/*.php'

      - name: Get PR number
        id: number
        uses: bcgov-nr/action-get-pr@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CI tests with coverage report
        if: ${{ steps.get-changed-files.outputs.added_modified }}
        uses: ./.github/actions/ci-tests-with-coverage
        with:
          php-version: ${{ env.PHP_VERSION }}
        
      - name: Code coverage report comment
        if: ${{ steps.get-changed-files.outputs.added_modified }}
        uses: ./.github/actions/php-coverage-comment
        with:
          changed-files: ${{ steps.get-changed-files.outputs.added_modified }}
          pr-number: ${{ steps.number.outputs.pr }}
