name: PHP tests

on:
  pull_request

jobs:
  get-woocommerce-versions:
    runs-on: ubuntu-22.04
    outputs:
        woocommerce-versions-json: ${{ steps.get-released-woocommerce-versions.outputs.versions-json }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get WooCommerce plugin versions
        id: get-released-woocommerce-versions
        uses: ./.github/actions/get-wordpress-plugin-versions
        with:
          plugin-slug: woocommerce
          version-count: 3
  get-wordpress-versions:
    runs-on: ubuntu-22.04
    outputs:
      wordpress-versions-json: ${{ steps.get-wordpress-versions.outputs.versions-json }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get WordPress versions
        id: get-wordpress-versions
        uses: ./.github/actions/get-wordpress-versions
        with:
          version-count: 3

  test:
    runs-on: ubuntu-22.04
    needs: [ get-woocommerce-versions, get-wordpress-versions ]
    strategy:
      fail-fast:    false
      max-parallel: 16
      matrix:
        woocommerce_support_policy: [ 'L', 'L-1', 'L-2' ]
        wordpress_support_policy:   [ 'L', 'L-1', 'L-2' ]
        php_support_policy:         [ 'L', 'L-1', 'L-2', 'L-3', '7.4' ]
        include:
          # WooCommerce
          - woocommerce_support_policy: L
            woocommerce: ${{ fromJson(needs.get-woocommerce-versions.outputs.woocommerce-versions-json)[0] }}
          - woocommerce_support_policy: L-1
            woocommerce: ${{ fromJson(needs.get-woocommerce-versions.outputs.woocommerce-versions-json)[1] }}
          - woocommerce_support_policy: L-2
            woocommerce: ${{ fromJson(needs.get-woocommerce-versions.outputs.woocommerce-versions-json)[2] }}
          # WordPress
          - wordpress_support_policy: L
            wordpress: ${{ fromJson(needs.get-wordpress-versions.outputs.wordpress-versions-json)[0] }}
          - wordpress_support_policy: L-1
            wordpress: ${{ fromJson(needs.get-wordpress-versions.outputs.wordpress-versions-json)[1] }}
          - wordpress_support_policy: L-2
            wordpress: ${{ fromJson(needs.get-wordpress-versions.outputs.wordpress-versions-json)[2] }}
          # PHP
          - php_support_policy: L
            php: '8.3'
          - php_support_policy: L-1
            php: '8.2'
          - php_support_policy: L-2
            php: '8.1'
          - php_support_policy: L-3
            php: '8.0'
          - php_support_policy: '7.4'
            php: '7.4'
        exclude: # incompatible versions of PHP, WordPress, and WooCommerce
          - woocommerce_support_policy: L
            wordpress_support_policy: L-2

    name: Stable (PHP=${{ matrix.php_support_policy }}, WP=${{ matrix.wordpress_support_policy }}, WC=${{ matrix.woocommerce_support_policy }})
    env:
      PHP_VERSION: ${{ matrix.php }} 
      WP_VERSION:  ${{ matrix.wordpress }}
      WC_VERSION:  ${{ matrix.woocommerce }}
    steps:
      - name: Testing with PHP=${{ matrix.php }}, WP=${{ matrix.wordpress }}, WC=${{ matrix.woocommerce }}
        uses: actions/checkout@v2

      - name: Set up dependencies caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2.34.1
        with:
          php-version: ${{ matrix.php }}
          coverage:    xdebug

      - name: Run CI checks
        run: bash bin/run-ci-tests.bash
        