name: E2E Tests

on:
  workflow_call:
    inputs:
      wp-version:
        type: string
        default: 'latest'
      wc-version:
        type: string
        default: 'latest'
      php-version:
        type: string
        default: '7.4'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        project: [ 'default', 'legacy', 'acss', 'optimized-checkout', 'blik', 'becs' ]

    name: E2E - ${{ matrix.project }} (WP=${{ inputs.wp-version }}, WC=${{ inputs.wc-version }}, PHP=${{ inputs.php-version }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP and Node
        uses: ./.github/actions/setup-env
        with:
          php-version: ${{ inputs.php-version }}

      - name: Build plugin package
        run: npm run build

      # E2E test environment
      - name: Prepare test environment
        env:
          GITHUB_TOKEN: ${{ secrets.E2E_GH_TOKEN }}
          STRIPE_PUB_KEY: ${{ matrix.checkout == 'blik' && secrets.E2E_STRIPE_PUBLISHABLE_KEY_PL || matrix.checkout == 'becs' && secrets.E2E_STRIPE_PUBLISHABLE_KEY_AU || secrets.E2E_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ matrix.checkout == 'blik' && secrets.E2E_STRIPE_SECRET_KEY_PL || matrix.checkout == 'becs' && secrets.E2E_STRIPE_SECRET_KEY_AU || secrets.E2E_STRIPE_SECRET_KEY }}
        run: npm run test:e2e-setup

      - name: Run E2E tests
        env:
          STRIPE_PUB_KEY: ${{ matrix.checkout == 'blik' && secrets.E2E_STRIPE_PUBLISHABLE_KEY_PL || matrix.checkout == 'becs' && secrets.E2E_STRIPE_PUBLISHABLE_KEY_AU || secrets.E2E_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ matrix.checkout == 'blik' && secrets.E2E_STRIPE_SECRET_KEY_PL || matrix.checkout == 'becs' && secrets.E2E_STRIPE_SECRET_KEY_AU || secrets.E2E_STRIPE_SECRET_KEY }}
        run: npm run test:e2e -- --project=${{ matrix.project }}

      - name: Upload E2E test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}-WP_${{ inputs.wp-version }}-WC_${{ inputs.wc-version }}-results
          path: tests/e2e/test-results
          if-no-files-found: ignore
          retention-days: 14